<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGL8lsnY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGL8lsnY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGL8lsnY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGL8lsnY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGL8lsnY\App_KernelDevDebugContainer([
    'container.build_hash' => 'GL8lsnY',
    'container.build_id' => 'a6c02fe7',
    'container.build_time' => 1590758826,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGL8lsnY');
